/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Represents a connection to a virtual camera. */
export declare class VirtualCamera {
  /**
   * Creates a new VirtualCamera instance.
   *
   * @param {backend} backend - The backend to use.
   */
  constructor(backend: Backend)
  /** Whether the virtual camera is currently running. */
  get isRunning(): boolean
  /** Starts the virtual camera. */
  start(): void
  /** Stops the virtual camera. */
  stop(): void
  /**
   * Submits an image to the virtual camera.
   *
   * Returns `true` if the frame was accepted (i.e., a process is consuming
   * the frames). Returns `false` if no application is reading from the camera.
   *
   * @param {number} width - Image width in pixels.
   * @param {number} height - Image height in pixels.
   * @param {ImageFormat} - Image data format.
   * @param {Uint8Array} - Image data in the specified format.
   *
   * @returns {boolean} `true` if the frame was accepted (i.e., a process is
   * consuming frames); `false` otherwise (i.e., no application is reading
   * from the virtual camera).
   */
  send(width: number, height: number, format: ImageFormat, image: Uint8Array): boolean
}
export type JsVirtualCamera = VirtualCamera

/** Supported virtual camera backends. */
export declare const enum Backend {
  /**
   * Unity Capture backend.
   * @see https://github.com/schellingb/UnityCapture
   */
  UnityCapture = 0
}

/** Image formats supported by the camera. */
export declare const enum ImageFormat {
  Rgba8Linear = 0
}
